CC=gcc 
CFLAGS=
DEPS = dependencies.h                				    # include directory
OBJ = server.o 						        		 	# source directory

%.o: %.c $(DEPS) 										# create .o files after compiling .c and .h files
	$(CC) -c -o $@ $< $(CFLAGS)

server: $(OBJ) 											# create out file
	$(CC) -o $@ $^ $(CFLAGS) 
