CC=gcc 
CFLAGS= -lcurses
DEPS = dependencies.h                                   # include directory
OBJ = client.o											# source directory

%.o: %.c $(DEPS) 										# create .o files after compiling .c and .h files
	$(CC) -c -o $@ $< $(CFLAGS)

client: $(OBJ) 											# create out file
	$(CC) -o $@ $^ $(CFLAGS) 
